### ISSUE TITLE
CREATE RESPONSE CLASS

### ISSUE THREAD

**Issue by Pobyeda** [Pobyeda/CSCI3916_Final_Project#3]
Create a response.js. Response should have Body message and unique identifier, should be some how related to 1-5 starts review. Maybe add int field review = 1-5 . So we will be able to search and pick needed one.

Use Movies.js, Users.js as a reference.

AC: 

Working class, no errors.

**Comment by jknight1725** [comment]
master branch pull requested
Initial commit made to response-schema-branch
