### ISSUE TITLE
WRITE BODY for 5 UNIQUE RESPONSES

### ISSUE THREAD

**Issue by Pobyeda** [Pobyeda/CSCI3916_Final_Project#4]
You need to write a body text for at least 5 responses at lease one for each type of review.

AC:
At lease 5 responses 
1 star response = 
2 star response = 
3 star response = 
4 star response = 
5 star response =

**Comment by jinbiaolian** [comment]
1 star response : We apologize that your experience was bad. We are working hard to change and improve our services. Please try us again later.
2 star response : We are sad to be informed that your experience was not as you expected, and we understand that, and we are working hard to improve our services.
3 star response : We appreciate your review and our team is working hard to improve our services. Please do try us again.
4 star response : We appreciate the review we will do everything to improve and get your 5 star review in the future.
5 star response : We are Thrilled that you were satisfied with our services and are exited to serve you furthermore.

**Comment by Pobyeda** [comment]
5 star review:
Thank you! 
4
