### ISSUE TITLE
SETUP HEROKU FOR THIS PROJECT

### ISSUE THREAD

**Issue by Pobyeda** [Pobyeda/CSCI3916_Final_Project#6]
Make sure HEROKU can deploy master branch. 
Create account for team if needed. Make sure everyone has access. 

AC: 
PROJECT MASTER Branch deployed to Heroku. Testing to prove it done. Make sure everyone in a team has access to Heroku.

**Comment by jknight1725** [comment]
HEROKU team account created
Invites sent to Team Members
HEROKU is connected to Github Master Branch
Automatic deploys to Master setup
